var annotated_dup =
[
    [ "doctest", "namespacedoctest.html", [
      [ "detail", "namespacedoctest_1_1detail.html", [
        [ "types", "namespacedoctest_1_1detail_1_1types.html", [
          [ "enable_if", "structdoctest_1_1detail_1_1types_1_1enable__if.html", null ],
          [ "enable_if< true, T >", "structdoctest_1_1detail_1_1types_1_1enable__if.html", "structdoctest_1_1detail_1_1types_1_1enable__if" ],
          [ "false_type", "structdoctest_1_1detail_1_1types_1_1false__type.html", null ],
          [ "is_array", "structdoctest_1_1detail_1_1types_1_1is__array.html", null ],
          [ "is_array< T[SIZE]>", "structdoctest_1_1detail_1_1types_1_1is__array.html", null ],
          [ "is_enum", "structdoctest_1_1detail_1_1types_1_1is__enum.html", null ],
          [ "is_pointer", "structdoctest_1_1detail_1_1types_1_1is__pointer.html", null ],
          [ "is_pointer< T * >", "structdoctest_1_1detail_1_1types_1_1is__pointer.html", null ],
          [ "is_rvalue_reference", "structdoctest_1_1detail_1_1types_1_1is__rvalue__reference.html", null ],
          [ "is_rvalue_reference< T && >", "structdoctest_1_1detail_1_1types_1_1is__rvalue__reference.html", null ],
          [ "remove_const", "structdoctest_1_1detail_1_1types_1_1remove__const.html", "structdoctest_1_1detail_1_1types_1_1remove__const" ],
          [ "remove_const< const T >", "structdoctest_1_1detail_1_1types_1_1remove__const.html", "structdoctest_1_1detail_1_1types_1_1remove__const" ],
          [ "remove_reference", "structdoctest_1_1detail_1_1types_1_1remove__reference.html", "structdoctest_1_1detail_1_1types_1_1remove__reference" ],
          [ "remove_reference< T & >", "structdoctest_1_1detail_1_1types_1_1remove__reference.html", "structdoctest_1_1detail_1_1types_1_1remove__reference" ],
          [ "remove_reference< T && >", "structdoctest_1_1detail_1_1types_1_1remove__reference.html", "structdoctest_1_1detail_1_1types_1_1remove__reference" ],
          [ "true_type", "structdoctest_1_1detail_1_1types_1_1true__type.html", null ],
          [ "underlying_type", "structdoctest_1_1detail_1_1types_1_1underlying__type.html", "structdoctest_1_1detail_1_1types_1_1underlying__type" ]
        ] ],
        [ "ContextScope", "classdoctest_1_1detail_1_1_context_scope.html", "classdoctest_1_1detail_1_1_context_scope" ],
        [ "ContextScopeBase", "structdoctest_1_1detail_1_1_context_scope_base.html", "structdoctest_1_1detail_1_1_context_scope_base" ],
        [ "deferred_false", "structdoctest_1_1detail_1_1deferred__false.html", null ],
        [ "ExceptionTranslator", "classdoctest_1_1detail_1_1_exception_translator.html", "classdoctest_1_1detail_1_1_exception_translator" ],
        [ "Expression_lhs", "structdoctest_1_1detail_1_1_expression__lhs.html", "structdoctest_1_1detail_1_1_expression__lhs" ],
        [ "ExpressionDecomposer", "structdoctest_1_1detail_1_1_expression_decomposer.html", "structdoctest_1_1detail_1_1_expression_decomposer" ],
        [ "filldata", "structdoctest_1_1detail_1_1filldata.html", null ],
        [ "filldata< const char[N]>", "structdoctest_1_1detail_1_1filldata.html", null ],
        [ "filldata< const void * >", "structdoctest_1_1detail_1_1filldata.html", null ],
        [ "filldata< T * >", "structdoctest_1_1detail_1_1filldata.html", null ],
        [ "filldata< T[N]>", "structdoctest_1_1detail_1_1filldata.html", null ],
        [ "has_insertion_operator", "structdoctest_1_1detail_1_1has__insertion__operator.html", null ],
        [ "has_insertion_operator< T, decltype(operator<<(declval< std::ostream & >(), declval< const T & >()), void())>", "structdoctest_1_1detail_1_1has__insertion__operator.html", null ],
        [ "IExceptionTranslator", "structdoctest_1_1detail_1_1_i_exception_translator.html", "structdoctest_1_1detail_1_1_i_exception_translator" ],
        [ "MessageBuilder", "structdoctest_1_1detail_1_1_message_builder.html", "structdoctest_1_1detail_1_1_message_builder" ],
        [ "RelationalComparator", "structdoctest_1_1detail_1_1_relational_comparator.html", "structdoctest_1_1detail_1_1_relational_comparator" ],
        [ "Result", "structdoctest_1_1detail_1_1_result.html", "structdoctest_1_1detail_1_1_result" ],
        [ "ResultBuilder", "structdoctest_1_1detail_1_1_result_builder.html", "structdoctest_1_1detail_1_1_result_builder" ],
        [ "should_stringify_as_underlying_type", "structdoctest_1_1detail_1_1should__stringify__as__underlying__type.html", null ],
        [ "StringMakerBase", "structdoctest_1_1detail_1_1_string_maker_base.html", null ],
        [ "StringMakerBase< true >", "structdoctest_1_1detail_1_1_string_maker_base.html", null ],
        [ "Subcase", "structdoctest_1_1detail_1_1_subcase.html", "structdoctest_1_1detail_1_1_subcase" ],
        [ "TestCase", "structdoctest_1_1detail_1_1_test_case.html", "structdoctest_1_1detail_1_1_test_case" ],
        [ "TestFailureException", "structdoctest_1_1detail_1_1_test_failure_exception.html", null ],
        [ "TestSuite", "structdoctest_1_1detail_1_1_test_suite.html", "structdoctest_1_1detail_1_1_test_suite" ]
      ] ],
      [ "Approx", "structdoctest_1_1_approx.html", "structdoctest_1_1_approx" ],
      [ "AssertData", "structdoctest_1_1_assert_data.html", "structdoctest_1_1_assert_data" ],
      [ "Contains", "classdoctest_1_1_contains.html", "classdoctest_1_1_contains" ],
      [ "Context", "classdoctest_1_1_context.html", "classdoctest_1_1_context" ],
      [ "ContextOptions", "structdoctest_1_1_context_options.html", "structdoctest_1_1_context_options" ],
      [ "CurrentTestCaseStats", "structdoctest_1_1_current_test_case_stats.html", "structdoctest_1_1_current_test_case_stats" ],
      [ "IContextScope", "structdoctest_1_1_i_context_scope.html", "structdoctest_1_1_i_context_scope" ],
      [ "IReporter", "structdoctest_1_1_i_reporter.html", "structdoctest_1_1_i_reporter" ],
      [ "IsNaN", "structdoctest_1_1_is_na_n.html", "structdoctest_1_1_is_na_n" ],
      [ "MessageData", "structdoctest_1_1_message_data.html", "structdoctest_1_1_message_data" ],
      [ "QueryData", "structdoctest_1_1_query_data.html", "structdoctest_1_1_query_data" ],
      [ "String", "classdoctest_1_1_string.html", "classdoctest_1_1_string" ],
      [ "StringMaker", "structdoctest_1_1_string_maker.html", null ],
      [ "SubcaseSignature", "structdoctest_1_1_subcase_signature.html", "structdoctest_1_1_subcase_signature" ],
      [ "TestCaseData", "structdoctest_1_1_test_case_data.html", "structdoctest_1_1_test_case_data" ],
      [ "TestCaseException", "structdoctest_1_1_test_case_exception.html", "structdoctest_1_1_test_case_exception" ],
      [ "TestRunStats", "structdoctest_1_1_test_run_stats.html", "structdoctest_1_1_test_run_stats" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "basic_istream", "classstd_1_1basic__istream.html", null ],
      [ "basic_ostream", "classstd_1_1basic__ostream.html", null ],
      [ "char_traits", "structstd_1_1char__traits.html", null ],
      [ "tuple", "classstd_1_1tuple.html", null ]
    ] ],
    [ "Arquivo", "class_arquivo.html", "class_arquivo" ],
    [ "Batalha_Naval", "class_batalha___naval.html", "class_batalha___naval" ],
    [ "CadastroJogadores", "class_cadastro_jogadores.html", "class_cadastro_jogadores" ],
    [ "Estatisticas", "class_estatisticas.html", "class_estatisticas" ],
    [ "Jogador", "class_jogador.html", "class_jogador" ],
    [ "Jogo_Da_Velha", "class_jogo___da___velha.html", "class_jogo___da___velha" ],
    [ "Jogo_De_Tabuleiro", "class_jogo___de___tabuleiro.html", "class_jogo___de___tabuleiro" ],
    [ "Lig_4", "class_lig__4.html", "class_lig__4" ],
    [ "Partida", "class_partida.html", "class_partida" ],
    [ "Placar", "class_placar.html", "class_placar" ],
    [ "Reversi", "class_reversi.html", "class_reversi" ],
    [ "Tutorial", "class_tutorial.html", "class_tutorial" ],
    [ "Validacao", "class_validacao.html", "class_validacao" ]
];